# -*- coding: utf-8 -*-
"""Myntra_Sales_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGD03gD1JBwa97HTseFjENq-cJ7RfXBw

# Myntra Sales Data Cleaning & Preparation

This notebook focuses on cleaning and preparing Myntra sales data for analysis and visualization.

## Key Steps:
- Data cleaning
- Data validation
- Feature engineering
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
from datetime import date

uploaded = files.upload()

df = pd.read_csv("Myntra Sales Analysis.csv")
df.head()

df.columns[23]

df.iloc[:, 23].unique()

df = df.loc[:, ~df.columns.str.contains('^Unnamed', case = False)]
df = df.drop(columns = ['index'])

"""Removed unnecessary columns generated during CSV import (e.g., 'Unnamed' columns) to clean the dataset."""

df.head()

df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')

df['date'] = pd.to_datetime(df['date'], errors = 'coerce')

df['ship_postal_code'] = df['ship_postal_code'].astype('Int64')
df['courier_status'] = df['courier_status'].fillna('Unkown')

df.isnull().sum()

df = df[df['amount'].notnull()].copy()

df['currency'] = df['currency'].fillna('INR')

df['promotion_ids'] = df['promotion_ids'].fillna('No Promotion')
df['fulfilled_by'] = df['fulfilled_by'].fillna('Unknown')

df['revenue'] = df['qty'] * df['amount']

df['month'] = df['date'].dt.month

"""Handled SettingWithCopyWarning by creating an explicit copy of the filtered DataFrame to ensure safe modifications."""

df.describe()

"""## Data Cleaning Steps

- Removed unnecessary columns ('index', unnamed columns)
- Standardized column names
- Converted date column to datetime format
- Handled missing values in key columns
- Created new features (revenue, month)
"""

df = df[df['qty'] > 0]

df = df[df['amount'] > 0]

df = df[df['revenue'] < 10000]

df = df[df['ship_postal_code'].notnull()]

df.describe()

"""## Data Quality Observations

- Removed records with zero quantity and zero amount
- Identified and filtered extreme revenue outliers
- Handled missing postal codes
- Observed that most orders consist of single items
- Dataset spans from March to June 2022
"""

df[df['revenue'] > 5000]

"""## Post-Cleaning Observations

- Removed invalid records (zero quantity and amount)
- Data distribution is now consistent and realistic
- Majority of transactions involve single-item purchases
- Revenue closely follows product price due to low quantity variation
- Dataset spans March to June 2022
"""

for col in df.columns:
  print(col)

df.rename(columns={
    'sales_channel_' : 'sales_channel'
}, inplace = True)

for col in df.columns:
  print(col)

df.to_csv("cleaned_myntra_sales_data.csv", index = False)

files.download("cleaned_myntra_sales_data.csv")

len(df.columns)

df['amount'] = pd.to_numeric(df['amount'], errors = 'coerce')

df['b2b'] = df['b2b'].astype(str).str.lower().map({'true': True, 'false': False})

df = df[df['qty'].notnull()]

df.to_csv("cleaned_myntra_data.csv", index = False)

files.download('cleaned_myntra_data.csv')

for i, col in enumerate(df.columns):
  print(i, col)

df = df[[
    'order_id',
    'date',
    'status',
    'fulfilment',
    'sales_channel',
    'ship_service_level',
    'style',
    'sku',
    'category',
    'size',
    'asin',
    'courier_status',
    'qty',
    'currency',
    'amount',
    'ship_city',
    'ship_state',
    'ship_postal_code',
    'ship_country',
    'promotion_ids',
    'fulfilled_by',
    'b2b',
    'revenue',
    'month'
]]

df['b2b'].unique()

df['b2b'] = df['b2b'].astype(str).str.lower().map({'true': True, 'false': False})

df.to_csv("myntra.csv", index = False)

files.download("myntra.csv")

df['month'] = pd.to_numeric(df['month'], errors = 'coerce').fillna(0).astype(int)

df['month'].unique()

df.to_csv("Myntra.csv", index = False)

files.download("Myntra.csv")