CREATE TABLE myntra_sales (
	order_id TEXT,
	date DATE,
	status TEXT,
	fulfilment TEXT,
	sales_channel TEXT,
	ship_service_level TEXT,
	style TEXT,
	sku TEXT,
	category TEXT,
	size TEXT,
	asin TEXT,
	courier_status TEXT,
	qty INT,
	currency TEXT,
	amount FLOAT,
	ship_city TEXT,
	ship_state TEXT,
	ship_postal_code TEXT,
	ship_country TEXT,
	promotion_ids TEXT,
	fulfilled_by TEXT,
	b2b BOOLEAN,
	revenue FLOAT,
	month INT
);